### ISSUE TITLE
Some Features won't work error on newest version v2022.8.23/v2022.8.24e

### ISSUE THREAD

**Issue by LudiGamer11** [HackerHansen/AmongUsCosmetics#11]
![image](https://user-images.githubusercontent.com/95187077/186504798-e6a020e4-6bdd-4747-bab7-8ea663c95f92.png)

**Comment by HackerHansen** [comment]
Hi, sorry for the late reply. I saw this on my phone a few days ago but I've been busy lately and totally forgot about this issue 😅 

The features still work, but it seems like they combined the cosmetic check into one function or something because the one patch seems to do the trick. I'll update it soon.

**Comment by HackerHansen** [comment]
Alright, I pushed the fix. There aren't any issues that I know of, but I barely spent any time on the code so there might be random issues so feel free to lmk if you find any weird bugs
