### ISSUE TITLE
Trojan 

### ISSUE THREAD

**Issue by SMS-COOLRAY126** [HackerHansen/AmongUsCosmetics#16]
Don't download. EXE file has a Trojan and is able to produce man in the middle attacks.
<img width="971" alt="image" src="https://github.com/user-attachments/assets/f510e809-06a8-45d2-b951-3ec8155f724b">

**Comment by HackerHansen** [comment]
From the "BEFORE MAKING AN ISSUE" section of the README: "_If you're worried that this program actually is a virus, you can check out the source code and compile the program yourself._"

This is GitHub, all the source code is provided. You can clone the repo, check all the source code yourself to prove there's no trojan, and build the exe. Your built exe (as well as the provided release exe) will flag some AVs as well since it's reading and modifying another process's memory (which is kind of how the entire thing works). If you're worried about the safety of the provided release exe you can disassemble it and take a look at that.

If you don't know what I just said (including what "source code" means), that's ok, but I would suggest laying off on accusing people of things you might not fully understand. It's good to raise concerns to clear up misunderstandings, but a straight accusation is almost never the way to go. This applies to the real world as well, not just GitHub. 

If you want to learn more, you can start by **asking a trusted adult who is good at computer stuff** (like the coding teacher at your school, if applicable, or a family friend who does coding as their job) to help explain this to you. You can show them this repository. They'll be able to read the code, explain to you why there are so many antivirus detections, and what you can do yourself next time to properly read the code and make sure the program is safe.
